# Generated by Django 4.1.4 on 2022-12-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure', models.IntegerField(verbose_name='Раход')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditure', to='vend.addres')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField(auto_now=True, verbose_name='Дата снятия счетчика')),
                ('number', models.IntegerField(verbose_name='Счетчик')),
                ('expenditure', models.IntegerField(verbose_name='Раход')),
                ('to_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Аренда')),
                ('toys', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Игрушки')),
                ('service', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='обслуживание')),
                ('service_description', models.TextField(verbose_name='обслуживание описание')),
                ('petrol', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='бензин')),
                ('other', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='прочие')),
                ('other_description', models.TextField(verbose_name='прочие описание')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addres', to='vend.addres')),
            ],
        ),
    ]
