# Generated by Django 4.1.4 on 2022-12-13 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='to_rent',
        ),
        migrations.AddField(
            model_name='addres',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addres',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='addres',
            name='to_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Аренда'),
        ),
        migrations.AddField(
            model_name='addres',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Expenditure',
        ),
    ]
