# Generated by Django 4.1.4 on 2022-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0002_remove_device_to_rent_addres_created_addres_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='expenditure',
            field=models.IntegerField(default=0, verbose_name='Раход'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default='Кран', max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='device',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='device',
            name='other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='прочие'),
        ),
        migrations.AlterField(
            model_name='device',
            name='other_description',
            field=models.TextField(blank=0, verbose_name='прочие описание'),
        ),
        migrations.AlterField(
            model_name='device',
            name='petrol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='бензин'),
        ),
        migrations.AlterField(
            model_name='device',
            name='service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='обслуживание'),
        ),
        migrations.AlterField(
            model_name='device',
            name='service_description',
            field=models.TextField(blank=True, verbose_name='обслуживание описание'),
        ),
        migrations.AlterField(
            model_name='device',
            name='toys',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Игрушки'),
        ),
    ]
