# Generated by Django 4.1.4 on 2022-12-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0002_alter_address_options_alter_counter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='vend.device'),
        ),
    ]
