# Generated by Django 4.1.4 on 2022-12-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0003_alter_counter_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vend.device'),
        ),
    ]
