# Generated by Django 4.1.4 on 2022-12-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0003_alter_device_expenditure_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addres',
            name='payment',
            field=models.CharField(choices=[('nal', 'Наличный расчет'), ('bez', 'Безналичный расчет')], default='bez', max_length=3, verbose_name='Оплата'),
        ),
    ]
