# Generated by Django 4.1.4 on 2022-12-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0004_addres_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addres',
            old_name='address',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='expenditure',
        ),
        migrations.RemoveField(
            model_name='device',
            name='month',
        ),
        migrations.RemoveField(
            model_name='device',
            name='number',
        ),
        migrations.RemoveField(
            model_name='device',
            name='other',
        ),
        migrations.RemoveField(
            model_name='device',
            name='other_description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='petrol',
        ),
        migrations.RemoveField(
            model_name='device',
            name='service',
        ),
        migrations.RemoveField(
            model_name='device',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='device',
            name='toys',
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateTimeField(auto_now=True, verbose_name='Дата снятия счетчика')),
                ('number', models.IntegerField(default=0, verbose_name='Счетчик')),
                ('expenditure', models.IntegerField(default=0, verbose_name='Раход')),
                ('toys', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Игрушки')),
                ('service', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='обслуживание')),
                ('service_description', models.TextField(blank=True, verbose_name='обслуживание описание')),
                ('petrol', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='бензин')),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='прочие')),
                ('other_description', models.TextField(blank=True, verbose_name='прочие описание')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counter', to='vend.device')),
            ],
        ),
    ]
