# Generated by Django 4.1.4 on 2022-12-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0004_alter_counter_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counter',
            new_name='Sensor',
        ),
    ]
