# Generated by Django 4.1.4 on 2022-12-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend', '0005_rename_address_addres_name_remove_device_expenditure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addres',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
